spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=tax;trustServerCertificate=true
spring.datasource.username=alvi
spring.datasource.password=alvi
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update
spring.main.allow-bean-definition-overriding=true

jwt.secret=secret
app.jwttoken.message='Login Successful'
app.controller.exception.message1='id and Password Empty'
app.controller.exception.message2='id and Password not found'
app.controller.exception.message3='id and Password Invalid'
